defmodule ShotTo.Ncpo do
  @moduledoc """
  Implementation of NCPO-LNF (the βη-long-normal Computability Path Order).

  Entry point: `ncpo_gt?/3` decides whether `s >^1_τ t` for two term IDs in
  the βη-long normal representation provided by
  `ShotDs.Stt.TermFactory`. This is the order referred to as `>_τ^1`
  (`NCPO-LNF`) in Definition 8 of Niederhauser & Middeldorp,
  *NCPO goes Beta-Eta-Long Normal Form*, 2025.

  The internal predicate `ncpo/6` implements the parameterised relation
  `>^{b,X}` (with a boolean `type_check?` toggling whether the type
  comparison `τ(s) ⪰_T τ(t)` is included, corresponding to the choice
  between `>^{b,X}` and `>^{b,X}_τ`). The helpers `bawo`, `awo`, `sswo`,
  `mul_ext?`, and `lex_ext?` mirror the ones in `OrderingLnf.hs` of the
  Haskell reference (`https://github.com/niedjoh/hrsterm`).

  ## Divergences from the reference

  Two points where this implementation diverges from the prototype at
  `hrsterm` deserve explicit note; both are conservative (they only ever
  *shrink* the ordering):

    * `lex_ext?/3` compares the residual tail of the right-hand side (the
      `u_j`'s) against `f(t̄)`, matching the Haskell reference and standard
      RPO convention. The paper's `⟨F=lex⟩` clause appears to say `t_j`
      instead of `u_j`, which we treat as a typo.

    * `mul_ext?/3` additionally requires the LHS-unique multiset
      `ss \\\\ ts` to be non-empty. Without that check, equal multisets
      compare as `greater` (since the universal quantifier is vacuously
      satisfied), which contradicts strictness. The Haskell reference
      omits this check; for termination of rewrite systems its absence is
      masked by other conditions on `ncpoMul`'s call sites, but for a
      decision procedure on pairs of terms it must be made explicit.

  ## Fresh variables

  Every time the algorithm opens a lambda (in `⟨Fλ⟩`, `⟨λ▷⟩`, `⟨λ=⟩`,
  `⟨λ≠⟩`) it does so by applying the abstraction to a freshly generated
  `ShotDs` free variable, keeping every intermediate term well-typed. This
  is more careful than the Haskell reference, which at `⟨λ≠⟩` reuses a
  fresh variable of the LHS binder's type on both sides — unproblematic in
  the untyped `ATerm` representation but ill-typed in a typed DAG.

  Callers that care about the size of the global ETS term pool should
  invoke `ShotDs.Stt.TermFactory.with_scratchpad/1` (or
  `with_scratchpad!`) around their calls; the fresh variables generated
  during a comparison will then be collected when the scratchpad exits.
  """

  alias ShotDs.Data.{Declaration, Term}
  alias ShotDs.Stt.TermFactory, as: TF
  alias ShotTo.Parameters
  alias ShotTo.TypeOrder

  @dialyzer nowarn_function: [contains_any_fv?: 2, bawo_descend: 6]

  @typedoc "The inductive-rule level parameter `b ∈ {0, 1}` of Definition 8."
  @type b :: 0 | 1

  @typedoc """
  Auxiliary variable set `X` of Definition 8. Each element is a fresh
  `ShotDs.Data.Declaration.free_var_t()` generated by lambda-opening.
  """
  @type x_set :: MapSet.t(Declaration.t())

  ##############################################################################
  # PUBLIC ENTRY POINT
  ##############################################################################

  @doc """
  Decides `s >^1_τ t`, i.e. whether the left term is strictly greater than
  the right in NCPO-LNF with the given parameters.

  Wraps the computation in a scratchpad (if none is active) so that the
  fresh variables introduced by lambda-opening do not pollute the global
  ETS table.
  """
  @spec ncpo_gt?(Term.term_id(), Term.term_id(), Parameters.t()) :: boolean()
  def ncpo_gt?(s_id, t_id, %Parameters{} = params)
      when is_integer(s_id) and is_integer(t_id) do
    with_scratchpad_bool(fn ->
      ncpo(1, MapSet.new(), s_id, t_id, true, params)
    end)
  end

  ##############################################################################
  # MAIN INDUCTIVE PREDICATE
  ##############################################################################

  @doc false
  @spec ncpo(b(), x_set(), Term.term_id(), Term.term_id(), boolean(), Parameters.t()) ::
          boolean()
  def ncpo(b, x, s_id, t_id, type_check?, params) do
    s = TF.get_term!(s_id)
    t = TF.get_term!(t_id)

    type_check_ok? = not type_check? or TypeOrder.type_geq?(s.type, t.type, params)

    type_check_ok? and dispatch_on_s(b, x, s_id, s, t_id, t, params)
  end

  # Case analysis on the head shape of s. NCPO-LNF is defined only for
  # *nonversatile* left-hand sides, i.e. fully applied constants or
  # lambda abstractions. A term headed by a variable is versatile and no
  # rule can fire.
  defp dispatch_on_s(b, x, s_id, %Term{bvars: []} = s, t_id, t, params) do
    case s.head.kind do
      :co -> ncpo_const_head(b, x, s_id, s, t_id, t, params)
      _variable -> false
    end
  end

  defp dispatch_on_s(b, x, s_id, %Term{bvars: [_ | _]} = s, t_id, t, params) do
    ncpo_lam_head(b, x, s_id, s, t_id, t, params)
  end

  ##############################################################################
  # RULES WITH A CONSTANT-HEADED LEFT-HAND SIDE
  ##############################################################################

  # s = f(t̄). Try ⟨FX⟩, ⟨F▷⟩, then dispatch on the shape of t.
  defp ncpo_const_head(b, x, s_id, s, t_id, t, params) do
    fx_rule?(x, t_id) or
      f_subterm_rule?(b, s.args, t_id, params) or
      ncpo_const_head_on_t(b, x, s_id, s, t_id, t, params)
  end

  # ⟨FX⟩:  f(t̄) >^{b,X} y↑η if y ∈ X.
  # Free variables in X are stored as Declarations; `TF.make_term/1` gives
  # their η-expanded term representation. Equality of term IDs is then
  # structural equality (modulo DAG sharing).
  defp fx_rule?(x, t_id) do
    Enum.any?(x, fn %Declaration{} = y -> TF.make_term(y) == t_id end)
  end

  # ⟨F▷⟩:  f(t̄) >^{b,X} v if ∃i. t_i ⊵^{nv}_b · ⊵_a · ≥^b_τ v.
  defp f_subterm_rule?(b, args, v_id, params) do
    Enum.any?(args, fn ti_id -> bawo(b, ti_id, v_id, params) end)
  end

  # Dispatch on t once ⟨FX⟩ and ⟨F▷⟩ have failed.
  defp ncpo_const_head_on_t(b, x, s_id, s, t_id, t, params) do
    case t do
      %Term{bvars: [], head: %Declaration{kind: :co}} ->
        ncpo_ff_case(b, x, s_id, s, t_id, t, params)

      %Term{bvars: [], head: %Declaration{kind: kind}} when kind in [:fv, :bv] ->
        # ⟨FV⟩ only fires at b = 1.
        b == 1 and ncpo_fv_rule(x, s_id, t, params)

      %Term{bvars: [_ | _]} ->
        ncpo_flam_rule(b, x, s_id, t_id, params)
    end
  end

  # ⟨F=mul⟩, ⟨F=lex⟩, ⟨F≻⟩:  f(t̄) >^{b,X} g(ū).
  defp ncpo_ff_case(b, x, s_id, s, _t_id, t, params) do
    f = s.head.name
    g = t.head.name
    ss = s.args
    ts = t.args

    equal_symbols? = Parameters.equiv?(params, f, g)
    same_status? = equal_symbols? and Parameters.status(params, f) == Parameters.status(params, g)

    cond do
      # ⟨F=⟩: f ≃_F g, same status. Compare argument lists by that status.
      same_status? ->
        same_head_compare(b, x, s_id, s, ss, ts, Parameters.status(params, f), params)

      # ⟨F≻⟩: f ≻_F g. Requires f(t̄) > u_i for every argument of the RHS.
      Parameters.gt?(params, f, g) ->
        Enum.all?(ts, fn u_id -> ncpo(b, x, s_id, u_id, false, params) end)

      # f ≃_F g with inconsistent status, or f, g unrelated in precedence
      # with no F=-rule applicable — no rule fires.
      true ->
        false
    end
  end

  # Helper for ⟨F=mul⟩ / ⟨F=lex⟩, the argument list comparison.
  defp same_head_compare(b, x, _s_id, _s, ss, ts, :mul, params) do
    mul_ext?(ss, ts, fn si, tj -> sswo?(b, x, si, tj, params) end)
  end

  defp same_head_compare(b, x, s_id, _s, ss, ts, :lex, params) do
    lex_ext?(
      ss,
      ts,
      fn si, tj -> sswo?(b, x, si, tj, params) end,
      fn tj -> ncpo(b, x, s_id, tj, false, params) end
    )
  end

  # ⟨FV⟩:  f(t̄) >^{1,X} y(ū) if f(t̄) >^{0,X} y↑η and f(t̄) >^{1,X} u_i for all i.
  defp ncpo_fv_rule(x, s_id, %Term{head: y_decl, args: us}, params) do
    y_eta_id = TF.make_term(y_decl)

    # y↑η check at b = 0 (no ⟨FV⟩ recursion allowed inside).
    head_ok? = ncpo(0, x, s_id, y_eta_id, false, params)

    head_ok? and
      Enum.all?(us, fn u_id -> ncpo(1, x, s_id, u_id, false, params) end)
  end

  # ⟨Fλ⟩:  f(t̄) >^{b,X} λy.v if f(t̄) >^{b,X∪{z}} v[y/z], z fresh with τ(z)=τ(y).
  #
  # Opening v[y/z] is implemented by applying the abstraction `t_id` (which
  # represents λy.v — possibly with further binders nested inside `v`) to a
  # fresh free variable `z` of the outermost binder's type. β-normalisation
  # inside `make_appl_term` handles the substitution; the resulting term
  # has one fewer outer binder and `z` occurs free wherever `y` used to be
  # bound.
  defp ncpo_flam_rule(b, x, s_id, t_id, params) do
    {z, opened_id} = open_outermost!(t_id)
    ncpo(b, MapSet.put(x, z), s_id, opened_id, false, params)
  end

  ##############################################################################
  # RULES WITH A LAMBDA-HEADED LEFT-HAND SIDE
  ##############################################################################

  # s = λx.u. Try ⟨λ▷⟩ with s opened on a fresh z, then ⟨λ=⟩/⟨λ≠⟩ if t is
  # itself an abstraction.
  defp ncpo_lam_head(b, x, s_id, _s, t_id, t, params) do
    {z_s, u_prime_id} = open_outermost!(s_id)

    # ⟨λ▷⟩: weak, type-checked NCPO from the opened body.
    lambda_subterm_rule?(b, x, u_prime_id, t_id, params) or
      case t do
        %Term{bvars: [bv_t | _]} ->
          if z_s.type == bv_t.type do
            # ⟨λ=⟩: reuse z_s since both binders share its type.
            z_term_id = TF.make_term(z_s)
            v_prime_id = TF.make_appl_term!(t_id, z_term_id)
            ncpo(b, x, u_prime_id, v_prime_id, false, params)
          else
            # ⟨λ≠⟩: open t with a fresh z_t of the correct type; use the
            # *original* λx.u on the left (per paper).
            {_z_t, v_prime_id} = open_outermost!(t_id)
            ncpo(b, x, s_id, v_prime_id, false, params)
          end

        _ ->
          false
      end
  end

  # ⟨λ▷⟩:  λx.u >^{b,X} v if u[x/z] ≥^{b,X}_τ v.
  defp lambda_subterm_rule?(b, x, u_prime_id, v_id, params) do
    ncpo_weak(b, x, u_prime_id, v_id, true, params)
  end

  ##############################################################################
  # WEAK VERSIONS (REFLEXIVE CLOSURE)
  ##############################################################################

  @doc false
  @spec ncpo_weak(b(), x_set(), Term.term_id(), Term.term_id(), boolean(), Parameters.t()) ::
          boolean()
  def ncpo_weak(b, x, s_id, t_id, type_check?, params) do
    # Term IDs are canonical (the factory memoises structurally equal
    # terms to the same integer), so `==` suffices for syntactic equality.
    s_id == t_id or ncpo(b, x, s_id, t_id, type_check?, params)
  end

  ##############################################################################
  # SUBTERM RELATIONS: bawo, awo, acc_subt
  ##############################################################################

  # `bawo(b, s, v)` ⇔ s (⊵^{nv}_b · ⊵_a · ≥^b_τ) v, where the first step may
  # take zero or more nonversatile descents. Used by ⟨F▷⟩.
  #
  # The set of *opened* variables introduced while descending through
  # lambdas inside s tracks the paper's "FV(t) ⊆ FV(s)" condition: a
  # reached subterm may only be compared with v if v does not reference
  # any of those opened variables (they live purely in the interior of s).
  defp bawo(b, s_id, v_id, params) do
    awo(b, s_id, v_id, params) or
      bawo_descend(b, s_id, v_id, MapSet.new(), _rec_case? = false, params)
  end

  defp bawo_descend(b, u_id, v_id, opened, rec_case?, params) do
    u = TF.get_term!(u_id)

    case u do
      # Lambda: open it with a fresh z and continue descending.
      %Term{bvars: [_ | _]} ->
        {z, body_id} = open_outermost!(u_id)
        bawo_descend(b, body_id, v_id, MapSet.put(opened, z), true, params)

      # Constant-headed fully applied term (nonversatile).
      %Term{bvars: [], head: %Declaration{kind: :co}, type: u_type, args: u_args} ->
        here? =
          rec_case? and
            TypeOrder.base?(u_type) and
            Parameters.basic?(params, u_type.goal) and
            not contains_any_fv?(v_id, opened) and
            awo(b, u_id, v_id, params)

        here? or
          Enum.any?(u_args, fn arg_id ->
            bawo_descend(b, arg_id, v_id, opened, true, params)
          end)

      # Variable-headed: versatile, descent cannot continue.
      %Term{bvars: []} ->
        false
    end
  end

  # Returns true if the term with the given ID mentions any of the given
  # free-variable declarations.
  defp contains_any_fv?(_term_id, opened) when opened == %MapSet{}, do: false

  defp contains_any_fv?(term_id, opened) do
    %Term{fvars: fvars} = TF.get_term!(term_id)
    Enum.any?(fvars, fn fv -> MapSet.member?(opened, fv) end)
  end

  # `awo(b, s, v)` ⇔ s ≥^b_τ v OR there is an accessible subterm of s that
  # stands in `awo` with v. X is fixed at ∅ inside `awo`.
  defp awo(b, s_id, v_id, params) do
    ncpo_weak(b, MapSet.new(), s_id, v_id, true, params) or
      acc_subt(b, s_id, v_id, params)
  end

  # Descends through the accessible argument positions of s, using `awo`
  # as the base-case comparator at each step.
  defp acc_subt(b, s_id, v_id, params) do
    case TF.get_term!(s_id) do
      %Term{bvars: [], head: %Declaration{kind: :co, name: f}, args: args} ->
        args
        |> Enum.with_index(1)
        |> Enum.any?(fn {arg_id, i} ->
          Parameters.accessible?(params, f, i) and
            awo(b, arg_id, v_id, params)
        end)

      _ ->
        false
    end
  end

  ##############################################################################
  # STRUCTURALLY SMALLER + WEAK ORIENT (sswo)
  ##############################################################################

  # `sswo(b, X, s, t)` ⇔ s ≥^b_τ t OR (τ(s) is a base sort a and there is
  # an accessible subterm u of s together with variables x_1, …, x_n ∈ X
  # of admissible types with u x_1 … x_n = t).
  #
  # Used as the base comparator of `mul_ext?` and `lex_ext?` in ⟨F=mul⟩ /
  # ⟨F=lex⟩ (the union `>^b_τ ∪ ▷^X_@ · →!_β` of Figure 1). Because our
  # terms are always kept in βη-long NF, the `→!_β` step is absorbed by
  # `TF.make_appl_term!` and structural equality suffices for the match.
  defp sswo?(b, x, s_id, t_id, params) do
    ncpo_weak(b, MapSet.new(), s_id, t_id, true, params) or
      structurally_smaller_app?(b, x, s_id, t_id, params)
  end

  defp structurally_smaller_app?(_b, x, s_id, t_id, params) do
    s = TF.get_term!(s_id)

    TypeOrder.base?(s.type) and
      acc_subt_apply(s_id, t_id, s.type.goal, x, params)
  end

  # Walks the accessible-subterm tree of `s_id` and, at every step, asks
  # whether the current subterm can be extended by a sequence of variables
  # from X to produce the target `t_id`.
  defp acc_subt_apply(s_id, t_id, base_sort, x, params) do
    case TF.get_term!(s_id) do
      %Term{bvars: [], head: %Declaration{kind: :co, name: f}, args: args} ->
        args
        |> Enum.with_index(1)
        |> Enum.any?(fn {u_id, i} ->
          Parameters.accessible?(params, f, i) and
            (try_apply_vars_match?(u_id, t_id, base_sort, x) or
               acc_subt_apply(u_id, t_id, base_sort, x, params))
        end)

      _ ->
        false
    end
  end

  # Tries all tuples (x_1, …, x_n) ∈ X^n matching the argument types of
  # `u_id` and checks whether any of the resulting βη-long-NF applications
  # is syntactically equal to `t_id`.
  defp try_apply_vars_match?(u_id, t_id, base_sort, x) do
    %Term{type: u_type} = TF.get_term!(u_id)

    cond do
      # u must ultimately return the same base sort as s.
      u_type.goal != base_sort ->
        false

      # And the base sort must not appear in any of u's argument types
      # (Pos_a(T_i) = ∅ in the paper).
      Enum.any?(u_type.args, fn arg_type -> TypeOrder.occurs_in?(base_sort, arg_type) end) ->
        false

      true ->
        arg_types = u_type.args

        candidates =
          Enum.map(arg_types, fn arg_type ->
            Enum.filter(x, fn %Declaration{type: vt} -> vt == arg_type end)
          end)

        if Enum.any?(candidates, &Enum.empty?/1) do
          false
        else
          candidates
          |> all_combinations()
          |> Enum.any?(fn var_list ->
            var_terms = Enum.map(var_list, &TF.make_term/1)
            TF.fold_apply!(u_id, var_terms) == t_id
          end)
        end
    end
  end

  defp all_combinations([]), do: [[]]

  defp all_combinations([xs | rest]) do
    rest_combos = all_combinations(rest)
    for x <- xs, r <- rest_combos, do: [x | r]
  end

  ##############################################################################
  # MULTISET AND LEXICOGRAPHIC EXTENSIONS
  ##############################################################################

  @doc false
  @spec mul_ext?([Term.term_id()], [Term.term_id()], (Term.term_id(), Term.term_id() -> boolean())) ::
          boolean()
  def mul_ext?(ss, ts, comp) do
    ss_minus_ts = multiset_diff(ss, ts)
    ts_minus_ss = multiset_diff(ts, ss)

    # Multiset extension of a strict order on term IDs. The strictness
    # requirement translates to "ss \\ ts must be non-empty" — otherwise
    # an identical-multiset pair would vacuously satisfy the universal
    # quantifier below. The Haskell reference omits this check; see the
    # module docs for context.
    not Enum.empty?(ss_minus_ts) and
      Enum.all?(ts_minus_ss, fn t ->
        Enum.any?(ss_minus_ts, fn s -> comp.(s, t) end)
      end)
  end

  @doc false
  @spec lex_ext?(
          [Term.term_id()],
          [Term.term_id()],
          (Term.term_id(), Term.term_id() -> boolean()),
          (Term.term_id() -> boolean())
        ) :: boolean()
  # Lists of unequal length: the reference treats this as a failure rather
  # than e.g. length-comparison; we follow that convention.
  def lex_ext?([], _, _, _), do: false
  def lex_ext?(_, [], _, _), do: false

  def lex_ext?([si | ss_tail], [ti | ts_tail], comp, dominance) do
    if si == ti do
      lex_ext?(ss_tail, ts_tail, comp, dominance)
    else
      comp.(si, ti) and Enum.all?(ts_tail, dominance)
    end
  end

  # List-based multiset difference. For small argument lists this linear
  # scan is easily fast enough; a grouped-count implementation would buy
  # little on the typical RHS/LHS sizes encountered in NCPO.
  defp multiset_diff(xs, ys) do
    Enum.reduce(ys, xs, fn y, acc -> List.delete(acc, y) end)
  end

  ##############################################################################
  # LAMBDA OPENING
  ##############################################################################

  # Opens the outermost abstraction of the given term by applying it to a
  # freshly generated free variable of the binder's type. Returns the pair
  # of (the fresh variable's declaration, the resulting term's ID).
  #
  # The ShotDs term factory's β-reduction inside `make_appl_term!` strips
  # the outer binder and substitutes the fresh variable for the bound
  # variable; the result remains in βη-long normal form.
  @spec open_outermost!(Term.term_id()) :: {Declaration.free_var_t(), Term.term_id()}
  defp open_outermost!(term_id) do
    %Term{bvars: [%Declaration{type: bv_type} | _]} = TF.get_term!(term_id)
    z = Declaration.fresh_var(bv_type)
    z_term_id = TF.make_term(z)
    {z, TF.make_appl_term!(term_id, z_term_id)}
  end

  ##############################################################################
  # SCRATCHPAD WRAPPER (boolean-returning variant of TF.with_scratchpad!/1)
  ##############################################################################

  # `TF.with_scratchpad!/1` is designed to commit a final term ID back to
  # the global pool; we just want a boolean. This wrapper mirrors its
  # ownership logic without any commit.
  defp with_scratchpad_bool(fun) when is_function(fun, 0) do
    own_scratchpad? = is_nil(Process.get(:term_scratchpad))
    if own_scratchpad?, do: TF.start_scratchpad()

    try do
      fun.()
    after
      if own_scratchpad?, do: TF.stop_scratchpad()
    end
  end
end
